import js from "@eslint/js";
import tseslint from "typescript-eslint";

const nodeGlobals = {
  console: "readonly",
  process: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  fetch: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  AbortSignal: "readonly",
  Buffer: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  module: "readonly",
  require: "readonly",
  exports: "readonly",
  global: "readonly",
  crypto: "readonly",
  Response: "readonly",
  Request: "readonly",
  Headers: "readonly",
  FormData: "readonly",
  Blob: "readonly",
  File: "readonly",
  Event: "readonly",
  EventTarget: "readonly",
  TextEncoder: "readonly",
  TextDecoder: "readonly",
  ReadableStream: "readonly",
  WritableStream: "readonly",
  Date: "readonly",
  Map: "readonly",
  Set: "readonly",
  Promise: "readonly",
  RegExp: "readonly",
  Error: "readonly",
  JSON: "readonly",
  Math: "readonly",
  parseInt: "readonly",
  parseFloat: "readonly",
  isNaN: "readonly",
  isFinite: "readonly",
  encodeURIComponent: "readonly",
  decodeURIComponent: "readonly",
  document: "readonly",
  window: "readonly",
  localStorage: "readonly",
  navigator: "readonly",
  self: "readonly",
  globalThis: "readonly",
};

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/drizzle/**",
      "**/.claude/**",
      "**/next.config.*",
      "**/postcss.config.*",
      "**/tailwind.config.*",
      "**/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: { globals: nodeGlobals },
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-require-imports": "off",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-useless-assignment": "off",
    },
  },
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    languageOptions: { globals: nodeGlobals },
    rules: {
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-useless-assignment": "off",
    },
  },
];
